clear 
clc 
close all 

% syms M(a,a) M(a,b) M(a,c) M(a,d) M(a,e) M(a,M) M(a,g)...
%      M(b,a) M(b,b) M(b,c) M(b,d) M(b,e) M(b,M) M(b,g)...
%      M(c,a) M(c,b) M(c,c) M(c,d) M(c,e) M(c,M) M(c,g)...
%      M(d,a) M(d,b) M(d,c) M(d,d) M(d,e) M(d,M) M(d,g)...
%      M(e,a) M(e,b) M(e,c) M(e,d) M(e,e) M(e,M) M(e,g)...
%      M(M,a) M(M,b) M(M,c) M(M,d) M(M,e) M(M,M) M(M,g)...
%      M(g,a) M(g,b) M(g,c) M(g,d) M(g,e) M(g,M) M(g,g)

% M = [M(a,a),M(a,b),M(a,c),M(a,d),M(a,e),M(a,M),M(a,g); ...
%      M(b,a),M(b,b),M(b,c),M(b,d),M(b,e),M(b,M),M(b,g); ...
%      M(c,a),M(c,b),M(c,c),M(c,d),M(c,e),M(c,M),M(c,g); ...
%      M(d,a),M(d,b),M(d,c),M(d,d),M(d,e),M(d,M),M(d,g); ...
%      M(e,a),M(e,b),M(e,c),M(e,d),M(e,e),M(e,M),M(e,g); ...
%      M(M,a),M(M,b),M(M,c),M(M,d),M(M,e),M(M,M),M(M,g); ...
%      M(g,a),M(g,b),M(g,c),M(g,d),M(g,e),M(g,M),M(g,g)];

syms M [6 6]
detM = simplify(det(M))
